version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.13.2
    steps:
      - checkout
      - run:
          name: Run Python unittests
          command: python -m unittest TestTriangle

workflows:
  test-workflow:
    jobs:
      - test
